#!/usr/bin/env python3
"""
Generate ``KernelBench/stress_refs/{large,awkward,xl}/level{1,2,3}/popcorn/*.py``
from canonical ``KernelBench/level{N}/popcorn/*.py`` using conservative
hyperparameter scaling (seq/batch/graph/matmul dims). Re-run after editing
logic or adding new popcorn problems.

  uv run python scripts/gen_popcorn_stress_refs.py
"""

from __future__ import annotations

import ast
import os
import sys

REPO_TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KERNEL_BENCH = os.path.join(REPO_TOP, "KernelBench")
SRC_POPCORN = os.path.join(KERNEL_BENCH, "level{level}", "popcorn")
DST_ROOT = os.path.join(KERNEL_BENCH, "stress_refs")
TIERS = ("large", "awkward", "xl")

sys.path.insert(0, os.path.join(REPO_TOP, "src"))
from kernelbench.popcorn_scaling import has_pair_seq2, transform_int  # noqa: E402


def _maybe_transform_assign(node: ast.Assign, tier: str, pair_attention: bool) -> ast.Assign:
    """Transform a single Assign node (caller ensures module-level)."""
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return node
    name = node.targets[0].id
    if not isinstance(node.value, ast.Constant) or not isinstance(node.value.value, int):
        return node
    new_val = transform_int(name, node.value.value, tier, pair_attention=pair_attention)
    if new_val == node.value.value:
        return node
    new_node = ast.Assign(
        targets=node.targets,
        value=ast.Constant(value=new_val),
        lineno=node.lineno,
        col_offset=node.col_offset,
    )
    return new_node


def _process_file(src_path: str, dst_path: str, tier: str) -> None:
    with open(src_path, encoding="utf-8") as f:
        src = f.read()
    pair = has_pair_seq2(src)
    tree = ast.parse(src)
    new_body: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.Assign):
            new_body.append(_maybe_transform_assign(node, tier, pair))
        else:
            new_body.append(node)
    tree.body = new_body
    ast.fix_missing_locations(tree)
    out = ast.unparse(tree)
    header = (
        f"# AUTO-GENERATED by scripts/gen_popcorn_stress_refs.py ({tier} tier).\n"
        f"# Source: {os.path.relpath(src_path, REPO_TOP)}\n\n"
    )
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(header + out)
        if not out.endswith("\n"):
            f.write("\n")


def main() -> int:
    levels = (1, 2, 3)
    n = 0
    for level in levels:
        pdir = SRC_POPCORN.format(level=level)
        if not os.path.isdir(pdir):
            print(f"[gen] skip missing {pdir}", file=sys.stderr)
            continue
        for fn in sorted(os.listdir(pdir)):
            if not fn.endswith(".py"):
                continue
            src_path = os.path.join(pdir, fn)
            if not os.path.isfile(src_path):
                continue
            for tier in TIERS:
                dst_path = os.path.join(
                    DST_ROOT, tier, f"level{level}", "popcorn", fn
                )
                _process_file(src_path, dst_path, tier)
                n += 1
    print(f"[gen] wrote {n} files under {DST_ROOT} ({len(TIERS)} tiers × problems).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
