#!/usr/bin/env python3
"""
Generate ``KernelBench/stress_refs2/{large,awkward,xl}/level{1,2,3,4}/popcorn2/*.py``.

- ``large``: copy of popcorn2 (already large-tier module centers).
- ``awkward`` / ``xl``: AST scale module-level ints from popcorn2 sources.

  uv run python scripts/gen_popcorn2_stress_refs.py
"""

from __future__ import annotations

import ast
import os
import shutil
import sys

REPO_TOP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KERNEL_BENCH = os.path.join(REPO_TOP, "KernelBench")
SRC_DIR = os.path.join(KERNEL_BENCH, "level{level}", "popcorn2")
DST_ROOT = os.path.join(KERNEL_BENCH, "stress_refs2")
LEVELS = (1, 2, 3, 4)
TIERS = ("large", "awkward", "xl")

sys.path.insert(0, os.path.join(REPO_TOP, "src"))
from kernelbench.popcorn_scaling import has_pair_seq2, transform_int  # noqa: E402


def _maybe_transform_assign(
    node: ast.Assign, tier: str, pair_attention: bool
) -> ast.Assign:
    if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
        return node
    name = node.targets[0].id
    if not isinstance(node.value, ast.Constant) or not isinstance(node.value.value, int):
        return node
    if tier == "large":
        return node
    new_val = transform_int(name, node.value.value, tier, pair_attention=pair_attention)
    if new_val == node.value.value:
        return node
    return ast.Assign(
        targets=node.targets,
        value=ast.Constant(value=new_val),
        lineno=node.lineno,
        col_offset=node.col_offset,
    )


def _write_large_copy(src_path: str, dst_path: str) -> None:
    with open(src_path, encoding="utf-8") as f:
        src = f.read()
    header = (
        f"# AUTO-GENERATED by scripts/gen_popcorn2_stress_refs.py (large tier = popcorn2).\n"
        f"# Source: {os.path.relpath(src_path, REPO_TOP)}\n\n"
    )
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(header + src)
        if not src.endswith("\n"):
            f.write("\n")


def _write_transformed(src_path: str, dst_path: str, tier: str) -> None:
    with open(src_path, encoding="utf-8") as f:
        src = f.read()
    pair = has_pair_seq2(src)
    tree = ast.parse(src)
    new_body: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.Assign):
            new_body.append(_maybe_transform_assign(node, tier, pair))
        else:
            new_body.append(node)
    tree.body = new_body
    ast.fix_missing_locations(tree)
    out = ast.unparse(tree)
    header = (
        f"# AUTO-GENERATED by scripts/gen_popcorn2_stress_refs.py ({tier} tier).\n"
        f"# Source: {os.path.relpath(src_path, REPO_TOP)}\n\n"
    )
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(header + out)
        if not out.endswith("\n"):
            f.write("\n")


def main() -> int:
    if os.path.isdir(DST_ROOT):
        shutil.rmtree(DST_ROOT)
    n = 0
    for level in LEVELS:
        src_dir = SRC_DIR.format(level=level)
        if not os.path.isdir(src_dir):
            print(f"[stress_refs2] skip missing {src_dir}", file=sys.stderr)
            continue
        for fn in sorted(os.listdir(src_dir)):
            if not fn.endswith(".py"):
                continue
            src_path = os.path.join(src_dir, fn)
            for tier in TIERS:
                dst_path = os.path.join(
                    DST_ROOT, tier, f"level{level}", "popcorn2", fn
                )
                if tier == "large":
                    _write_large_copy(src_path, dst_path)
                else:
                    _write_transformed(src_path, dst_path, tier)
                n += 1
    print(f"[stress_refs2] wrote {n} files under {DST_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
